export const AIRTABLE_GET_KEYWORDS_REQUESTED = 'AIRTABLE_GET_KEYWORDS_REQUESTED';
export const AIRTABLE_GET_KEYWORDS_SUCCEEDED = 'AIRTABLE_GET_KEYWORDS_SUCCEEDED';
export const AIRTABLE_GET_KEYWORDS_FAILED = 'AIRTABLE_GET_KEYWORDS_FAILED';
export const AIRTABLE_GET_KEYWORDS_DISMISSED = 'AIRTABLE_GET_KEYWORDS_DISMISSED';

export const BOARD_ADD = 'BOARD_ADD';
export const BOARD_REMOVE = 'BOARD_REMOVE';
export const BOARD_SHOWADVICE = 'BOARD_SHOWADVICE';

export const FEEDBACK_SEND_REQUESTED = 'FEEDBACK_SEND_REQUESTED';
export const FEEDBACK_SEND_SUCCEEDED = 'FEEDBACK_SEND_SUCCEEDED';
export const FEEDBACK_SEND_FAILED = 'FEEDBACK_SEND_FAILED';
export const FEEDBACK_SEND_DISMISSED = 'FEEDBACK_SEND_DISMISSED';

export const INFO_GET_REQUESTED = 'INFO_GET_REQUEST';
export const INFO_GET_SUCCEEDED = 'INFO_GET_SUCCEEDED';
export const INFO_GET_FAILED = 'INFO_GET_FAILED';
export const INFO_GET_DISMISSED = 'INFO_GET_DISMISSED';

export const MODAL_SET_OPEN = 'MODAL_SET_OPEN';
export const MODAL_SEEN = 'MODAL_SEEN';

export const PEOPLE_GET_REQUEST = 'PEOPLE_GET_REQUEST';
export const PEOPLE_GET_SUCCEEDED = 'PEOPLE_GET_SUCCEEDED';
export const PEOPLE_GET_FAILED = 'PEOPLE_GET_FAILED';
export const PEOPLE_GET_DISMISS = 'PEOPLE_GET_DISMISS';

export const STARTUPS_REQUESTED = 'STARTUPS_REQUESTED';
export const STARTUPS_SUCCEEDED = 'STARTUPS_SUCCEEDED';
export const STARTUPS_FAILED = 'STARTUPS_FAILED';
export const STARTUPS_DISMISSED = 'STARTUPS_DISMISSED';

export const FOUNDERS_REQUESTED = 'FOUNDERS_REQUESTED';
export const FOUNDERS_SUCCEEDED = 'FOUNDERS_SUCCEEDED';
export const FOUNDERS_FAILED = 'FOUNDERS_FAILED';
export const FOUNDERS_COMPLETED = 'FOUNDERS_COMPLETED';
export const FOUNDERS_DISMISSED = 'FOUNDERS_DISMISSED';

export const PERSON_PUT_INVALID_REQUESTED = 'PERSON_PUT_INVALID_REQUESTED';
export const PERSON_PUT_INVALID_SUCCEEDED = 'PERSON_PUT_INVALID_SUCCEEDED';
export const PERSON_PUT_INVALID_FAILED = 'PERSON_PUT_INVALID_FAILED';
export const PERSON_CLEAR_INVALID = 'PERSON_CLEAR_INVALID';

export const PUBLIC_GET_INVESTORS_REQUESTED = 'PUBLIC_GET_INVESTORS_REQUESTED';
export const PUBLIC_GET_INVESTORS_SUCCEEDED = 'PUBLIC_GET_INVESTORS_SUCCEEDED';
export const PUBLIC_GET_INVESTORS_FAILED = 'PUBLIC_GET_INVESTORS_FAILED';
export const PUBLIC_GET_INVESTORS_DISMISSED = 'PUBLIC_GET_INVESTORS_DISMISSED';

export const PUBLIC_POST_INTRO_REQUESTED = 'PUBLIC_POST_INTRO_REQUESTED';
export const PUBLIC_POST_INTRO_SUCCEEDED = 'PUBLIC_POST_INTRO_SUCCEEDED';
export const PUBLIC_POST_INTRO_FAILED = 'PUBLIC_POST_INTRO_FAILED';
export const PUBLIC_POST_INTRO_DISMISSED = 'PUBLIC_POST_INTRO_DISMISSED';

export const PUBLIC_GET_PROFILE_REQUESTED = 'PUBLIC_GET_PROFILE_REQUESTED';
export const PUBLIC_GET_PROFILE_SUCCEEDED = 'PUBLIC_GET_PROFILE_SUCCEEDED';
export const PUBLIC_GET_PROFILE_FAILED = 'PUBLIC_GET_PROFILE_FAILED';
export const PUBLIC_GET_PROFILE_DISMISSED = 'PUBLIC_GET_PROFILE_DISMISSED';

export const PUBLIC_GET_USER_REQUESTED = 'PUBLIC_GET_USER_REQUESTED';
export const PUBLIC_GET_USER_SUCCEEDED = 'PUBLIC_GET_USER_SUCCEEDED';
export const PUBLIC_GET_USER_FAILED = 'PUBLIC_GET_USER_FAILED';
export const PUBLIC_GET_USER_DISMISSED = 'PUBLIC_GET_USER_DISMISSED';

export const SEARCH_GET_RESULTS_REQUESTED = 'SEARCH_GET_RESULTS_REQUESTED';
export const SEARCH_GET_RESULTS_SUCCEEDED = 'SEARCH_GET_RESULTS_SUCCEEDED';
export const SEARCH_GET_RESULTS_FAILED = 'SEARCH_GET_RESULTS_FAILED';
export const SEARCH_GET_RESULTS_DISMISSED = 'SEARCH_GET_RESULTS_DISMISSED';
export const SEARCH_CLEAR_RESULTS = 'SEARCH_CLEAR_RESULTS';

export const SEARCH_GET_RANDOM_REQUESTED = 'SEARCH_GET_RANDOM_REQUESTED';
export const SEARCH_GET_RANDOM_SUCCEEDED = 'SEARCH_GET_RANDOM_SUCCEEDED';
export const SEARCH_GET_RANDOM_FAILED = 'SEARCH_GET_RANDOM_FAILED';
export const SEARCH_GET_RANDOM_DISMISSED = 'SEARCH_GET_RANDOM_DISMISSED';
export const SEARCH_CLEAR_RANDOM = 'SEARCH_CLEAR_RANDOM';

export const SEARCH_SET_KEYWORDS = 'SEARCH_SET_KEYWORDS';
export const SEARCH_SET_ONLYLEADS = 'SEARCH_SET_ONLYLEADS';
export const SEARCH_SET_ONLYDIVERSE = 'SEARCH_SET_ONLYDIVERSE';
export const SEARCH_SET_ONLYOPEN = 'SEARCH_SET_ONLYOPEN';
export const SEARCH_SET_RAISE = 'SEARCH_SET_RAISE';
export const SEARCH_SET_LOCATION = 'SEARCH_SET_LOCATION';
export const SEARCH_TOGGLE_LOCATION = 'SEARCH_TOGGLE_LOCATION';
export const SEARCH_SET_ONLYLOCAL = 'SEARCH_SET_ONLYLOCAL';
export const SEARCH_SET_REMOTE = 'SEARCH_SET_REMOTE';
export const SEARCH_SET_SEARCHTEXT = 'SEARCH_SET_SEARCHTEXT';

export const SEARCH_SYNC_PREVQUERY = 'SEARCH_SYNC_PREVQUERY';

export const SEARCH_GET_EXTRAZIPCODES_REQUESTED = 'SEARCH_GET_EXTRAZIPCODES_REQUESTED';
export const SEARCH_GET_EXTRAZIPCODES_SUCCEEDED = 'SEARCH_GET_EXTRAZIPCODES_SUCCEEDED';
export const SEARCH_GET_EXTRAZIPCODES_FAILED = 'SEARCH_GET_EXTRAZIPCODES_FAILED';

export const USER_CREATE_REQUESTED = 'USER_CREATE_REQUESTED';
export const USER_CREATE_SUCCEEDED = 'USER_CREATE_SUCCEEDED';
export const USER_CREATE_FAILED = 'USER_CREATE_FAILED';
export const USER_CREATE_DISSMISSED = 'USER_CREATE_DISSMISSED';

/*
export const USER_VERIFYEMAIL_REQUESTED = 'USER_VERIFYEMAIL_REQUESTED';
export const USER_VERIFYEMAIL_SUCCEEDED = 'USER_VERIFYEMAIL_SUCCEEDED';
export const USER_VERIFYEMAIL_FAILED = 'USER_VERIFYEMAIL_FAILED';
export const USER_VERIFYEMAIL_DISSMISSED = 'USER_VERIFYEMAIL_DISSMISSED';
 */

export const USER_DELETE_REQUESTED = 'USER_DELETE_REQUESTED';
export const USER_DELETE_SUCCEEDED = 'USER_DELETE_SUCCEEDED';
export const USER_DELETE_FAILED = 'USER_DELETE_FAILED';
export const USER_DELETE_DISSMISSED = 'USER_DELETE_DISSMISSED';

export const USER_GET_MANUALINVESTORS_REQUESTED = 'USER_GET_MANUALINVESTORS_REQUESTED';
export const USER_GET_MANUALINVESTORS_SUCCEEDED = 'USER_GET_MANUALINVESTORS_SUCCEEDED';
export const USER_GET_MANUALINVESTORS_FAILED = 'USER_GET_MANUALINVESTORS_FAILED';
export const USER_GET_MANUALINVESTORS_DISMISSED = 'USER_GET_MANUALINVESTORS_DISMESSED';

export const USER_POST_MANUALINVESTOR_REQUESTED = 'USER_POST_MANUALINVESTOR_REQUESTED';
export const USER_POST_MANUALINVESTOR_SUCCEEDED = 'USER_POST_MANUALINVESTOR_SUCCEEDED';
export const USER_POST_MANUALINVESTOR_FAILED = 'USER_POST_MANUALINVESTOR_FAILED';
export const USER_POST_MANUALINVESTOR_DISMISSED = 'USER_POST_MANUALINVESTOR_DISMISSED';

export const USER_GET_PROFILE_REQUESTED = 'USER_GET_PROFILE_REQUESTED';
export const USER_GET_PROFILE_SUCCEEDED = 'USER_GET_PROFILE_SUCCEEDED';
export const USER_GET_PROFILE_FAILED = 'USER_GET_PROFILE_FAILED';
export const USER_GET_PROFILE_DISMISSED = 'USER_GET_PROFILE_DISMISSED';

export const USER_POST_PROFILE_REQUESTED = 'USER_POST_PROFILE_REQUESTED';
export const USER_POST_PROFILE_SUCCEEDED = 'USER_POST_PROFILE_SUCCEEDED';
export const USER_POST_PROFILE_FAILED = 'USER_POST_PROFILE_FAILED';
export const USER_POST_PROFILE_DISMISSED = 'USER_POST_PROFILE_DISMISSED';

export const USER_LOGIN_REQUESTED = 'USER_LOGIN_REQUESTED';
export const USER_LOGIN_SUCCEEDED = 'USER_LOGIN_SUCCEEDED';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_LOGIN_DISSMISSED = 'USER_LOGIN_DISSMISSED';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_SET_EDITNOTE = 'USER_SET_EDITNOTE';

export const USER_GET_INVESTORS_REQUESTED = 'USER_GET_INVESTORS_REQUESTED';
export const USER_GET_INVESTORS_SUCCEEDED = 'USER_GET_INVESTORS_SUCCEEDED';
export const USER_GET_INVESTORS_FAILED = 'USER_GET_INVESTORS_FAILED';
export const USER_GET_INVESTORS_DISMISSED = 'USER_GET_INVESTORS_DISMISSED';

export const USER_POST_INVESTOR_REQUESTED = 'USER_POST_INVESTOR_REQUESTED';
export const USER_POST_INVESTOR_SUCCEEDED = 'USER_POST_INVESTOR_SUCCEEDED';
export const USER_POST_INVESTOR_FAILED = 'USER_POST_INVESTOR_FAILED';
export const USER_POST_INVESTOR_DISMISSED = 'USER_POST_INVESTOR_DISMISSED';

export const USER_POST_SAFEADDINVESTORS_REQUESTED = 'USER_POST_SAFEADDINVESTORS_REQUESTED';
export const USER_POST_SAFEADDINVESTORS_SUCCEEDED = 'USER_POST_SAFEADDINVESTORS_SUCCEEDED';
export const USER_POST_SAFEADDINVESTORS_FAILED = 'USER_POST_SAFEADDINVESTORS_FAILED';
export const USER_POST_SAFEADDINVESTORS_DISMISSED = 'USER_POST_SAFEADDINVESTORS_DISMISSED';

export const USER_RESETPASSWORD_REQUESTED = 'USER_RESETPASSWORD_REQUESTED';
export const USER_RESETPASSWORD_SUCCEEDED = 'USER_RESETPASSWORD_SUCCEEDED';
export const USER_RESETPASSWORD_FAILED = 'USER_RESETPASSWORD_FAILED';
export const USER_RESETPASSWORD_DISSMISSED = 'USER_RESETPASSWORD_DISSMISSED';

export const USER_UPDATE_REQUESTED = 'USER_UPDATE_REQUESTED';
export const USER_UPDATE_SUCCEEDED = 'USER_UPDATE_SUCCEEDED';
export const USER_UPDATE_FAILED = 'USER_UPDATE_FAILED';
export const USER_UPDATE_DISSMISSED = 'USER_UPDATE_DISSMISSED';

export const USER_LOCAL_UPDATE_REQUESTED = 'USER_LOCAL_UPDATE_REQUESTED';
