export const AIRTABLE_GET_KEYWORDS_REQUESTED = 'AIRTABLE_GET_KEYWORDS_REQUESTED';
export const AIRTABLE_GET_KEYWORDS_SUCCEEDED = 'AIRTABLE_GET_KEYWORDS_SUCCEEDED';
export const AIRTABLE_GET_KEYWORDS_FAILED = 'AIRTABLE_GET_KEYWORDS_FAILED';

export const REHYDRATE = 'REHYDRATE';

export const SEARCH_GET_RESULTS_REQUESTED = 'SEARCH_GET_RESULTS_REQUESTED';
export const SEARCH_GET_RESULTS_SUCCEEDED = 'SEARCH_GET_RESULTS_SUCCEEDED';
export const SEARCH_GET_RESULTS_FAILED = 'SEARCH_GET_RESULTS_FAILED';

export const SEARCH_SET_KEYWORDS = 'SEARCH_SET_KEYWORDS';
export const SEARCH_SET_RAISE = 'SEARCH_SET_RAISE';
export const SEARCH_SET_LOCATION = 'SEARCH_SET_LOCATION';
export const SEARCH_SET_REMOTE = 'SEARCH_SET_REMOTE';


