export const SEARCH_SET_KEYWORDS = 'SEARCH_SET_KEYWORDS';
export const SEARCH_SET_RAISE = 'SEARCH_SET_RAISE';
export const SEARCH_SET_LOCATION = 'SEARCH_SET_LOCATION';
export const SEARCH_SET_STAGE = 'SEARCH_SET_STAGE';
